web:
  build: .
  links:
    - db:postgres
  environment:
    POSTGRES_HOST: postgres
    DEPOT_EMAIL:
    DEPOT_PASSWORD:
  ports:
    - "3000:3000"
    - "587:587"
  volumes:
    - .:/app

db:
  image: postgres
  environment:
    POSTGRES_USER: depot
    POSTGRES_PASSWORD: depot
